-- LIHAT DATABASE
SHOW DATABASES;

-- MENGGUANAKAN DATABASE mysql
USE mysql;

-- MELIHAT ISI TABEL DALAM DB mysql
SHOW TABLES;

-- MELIHAT DESKRIPSI DARI TABEL user
DESCRIBE user;

-- AMBIL ISI DARI KOLOM HOST, USER, PASSWORD
SELECT Host, User, Password FROM user;